spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TESTDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sys_assessment
spring.datasource.password=340$Uuxwp7Mcxo7Khy

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

spring.mvc.pathmatch.matching-strategy=ant-path-matcher


## logging
logging.file.name=logs/application.log
logging.level.root=INFO
logging.level.com.interview=DEBUG
